name: ci-project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  actor-checks:
    runs-on: ubuntu-latest
    steps:
      - name: "Check if action is autorized"
        run: |
          allowed="Imadlhannouni"
          if [[ ${{ github.actor }} != "$allowed" ]]; then
            echo "Unautorized actor"
            exit 1
          fi
          echo "Autorized"
  build:
    runs-on: ubuntu-latest
    needs: actor-checks
    steps:
      - uses: actions/checkout@v3

      - name: "node"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: "node"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm test
    notify:
    runs-on: ubuntu-latest
    needs: actor-check
    if: failure()
    steps:
      - name: Send email via Brevo API
        run: |
          curl -X POST "https://api.brevo.com/v3/smtp/email" \
          -H "accept: application/json" \
          -H "api-key: ${{ secrets.BREVO_API_KEY }}" \
          -H "content-type: application/json" \
          -d '{
            "sender": {"name":"GitHub Actions","email":"lhannouni05@gmail.com"},
            "to": [{"email":"lhannouni05@gmail.com"}],
            "subject":"Unauthorized push attempt detected",
            "htmlContent":"<h2>ACTION BLOQUÉE</h2><p>Utilisateur non autorisé : '${{ github.actor }}'</p><p>Repo : '${{ github.repository }}'</p><p>Branche : '${{ github.ref }}'</p>"
          }'
