name: ci-project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  actor-checks:
    runs-on: ubuntu-latest
    steps:
      - name: "Check if action is autorized"
        run: |
          allowed="Imadlhannouni"
          if [[ ${{ github.actor }} != "$allowed" ]]; then
            echo "Unautorized actor"
            exit 1
          fi
          echo "Autorized"
