name: ci-project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  actor-checks:
    runs-on: ubuntu-latest
    steps:
      - name: "Check if action is autorized"
        run: |
          allowed="Imadlhannouni"
          if [[ ${{ github.actor }} != "$allowed" ]]; then
            echo "Unautorized actor"
            exit 1
          fi
          echo "Autorized"
  build:
    runs-on: ubuntu-latest
    needs: actor-checks
    steps:
      - uses: actions/checkout@v3

      - name: "node"
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm install
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: "node"
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm install
      - run: npm test
